apiVersion: v1
kind: Pod
metadata:
  name: ldap
spec:
  automountServiceAccountToken: false
  restartPolicy: OnFailure
  containers:
    - name: 389ds
      image: quay.io/389ds/dirsrv:latest@sha256:3957092c9636fbcdea428b5ef0d3b4d36eae2df75fe8548c3553233ad27ed890
      imagePullPolicy: Always
      env:
        - name: DS_DM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-secret
              key: DS_DM_PASSWORD
        - name: DS_SUFFIX_NAME
          valueFrom:
            secretKeyRef:
              name: ldap-secret
              key: DS_SUFFIX_NAME
      resources:
        limits:
          cpu: 100m
          ephemeral-storage: 100Mi
          memory: 1024Mi
        requests:
          cpu: 10m
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_DAC_READ_SEARCH
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 389
        runAsNonRoot: true
        runAsUser: 389
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: ldap-volume
          mountPath: /data
  volumes:
    - name: ldap-volume
      persistentVolumeClaim:
        claimName: ldap-pvc
