apiVersion: v1
kind: Pod
metadata:
  name: ldap
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: OnFailure
  containers:
    - name: 389ds
      image: quay.io/389ds/dirsrv:latest
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 1024Mi
        requests:
          cpu: 10m
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 389
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: ldap-volume
          mountPath: /data
  volumes:
    - name: ldap-volume
      persistentVolumeClaim:
        claimName: ldap-pvc
