apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 2Gi
    requests:
      storage: 300Mi
