apiVersion: v1
kind: Pod
metadata:
  name: ldap
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: OnFailure
  containers:
    - name: 389ds
      image: quay.io/389ds/dirsrv:latest@sha256:9bde32d384fec888bc3b55613b2eda2a99d12985c94631c46e16f693d3ea6fc9
      imagePullPolicy: Always
      env:
        - name: DS_DM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ldap-secret
              key: DS_DM_PASSWORD
        - name: DS_SUFFIX_NAME
          valueFrom:
            secretKeyRef:
              name: ldap-secret
              key: DS_SUFFIX_NAME
      resources:
        limits:
          cpu: 100m
          memory: 1024Mi
        requests:
          cpu: 10m
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_DAC_READ_SEARCH
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 389
        runAsNonRoot: true
        runAsUser: 389
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: ldap-volume
          mountPath: /data
  volumes:
    - name: ldap-volume
      persistentVolumeClaim:
        claimName: ldap-pvc
