apiVersion: v1
kind: Pod
metadata:
  name: ci
spec:
  restartPolicy: OnFailure
  containers:
    - name: drone.io-runner
      image: docker.io/drone/drone-runner-docker:1.8@sha256:513891eb6c8b920c48266f6881402b9df5e3f7ec874a12cd87146ebfd1105bed
      imagePullPolicy: Always
      env:
        - name: DRONE_RPC_HOST
          valueFrom:
            secretKeyRef:
              name: ci-secret
              key: DRONE_RPC_HOST
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: ci-secret
              key: DRONE_RPC_SECRET
        - name: DRONE_RUNNER_CAPACITY
          value: "1"
        - name: DRONE_SERVER_HOST
          value: ci
        - name: DRONE_SERVER_PROTO
          value: http
      resources:
        limits:
          cpu: 900m
          memory: 24Gi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: docker.sock-hostpath
          mountPath: /var/run/docker.sock
    - name: drone.io-server
      image: docker.io/drone/drone:2.22@sha256:4d5e7f98278d02808c63358a214c4eb787d54f0a2f1fb60fbac8f47828d3558e
      imagePullPolicy: Always
      env:
        - name: DRONE_GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: ci-secret
              key: DRONE_GITHUB_CLIENT_ID
        - name: DRONE_GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: ci-secret
              key: DRONE_GITHUB_CLIENT_SECRET
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: ci-secret
              key: DRONE_RPC_SECRET
        - name: DRONE_SERVER_HOST
          value: drone.exploding-hamster.duckdns.org
        - name: DRONE_SERVER_PROTO
          value: https
        - name: DRONE_USER_FILTER
          value: MartinX3
      resources:
        limits:
          cpu: 100m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: ci-drone.io-server-data-volume
          mountPath: /data
  volumes:
    - name: ci-drone.io-server-data-volume
      persistentVolumeClaim:
        claimName: ci-drone.io-server-data-pvc
    - name: docker.sock-hostpath
      hostPath:
        path: /run/user/1000/podman/podman.sock
