apiVersion: v1
kind: Secret
metadata:
  name: ci-secret
type: Opaque
stringData:
  DRONE_GITHUB_CLIENT_ID: "978cfa71f047eaa40952"
  DRONE_GITHUB_CLIENT_SECRET: "H4Fx6bK%M8*2@#@2&49%3P2"
  DRONE_RPC_HOST: "exploding-hamster.duckdns.org"
  DRONE_RPC_SECRET: "85344578918b708e9fa34d468166753e68d816d6"
