apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-drone.io-server-data-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 4Gi
    requests:
      storage: 128Mi
