apiVersion: v1
kind: Pod
metadata:
  name: honeypot
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: OnFailure
  containers:
    - name: ssh
      image: lscr.io/linuxserver/endlessh:latest@sha256:29d971f3600fad22be10ce7d00030a0c3e40565a8a384891ce940140630933ee
      imagePullPolicy: Always
      env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: "Etc/UTC"
      ports:
        - containerPort: 2222
          hostPort: 20
          name: ssh
        - containerPort: 2222
          hostPort: 21
          name: ssh
        - containerPort: 2222
          hostPort: 22
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 990
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 1024
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 1025
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 1026
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 1027
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 1028
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 1029
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 1030
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 2222
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 8443
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 65530
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 65531
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 65532
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 65533
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 65534
          name: ssh
          protocol: TCP
        - containerPort: 2222
          hostPort: 65535
          name: ssh
          protocol: TCP
      resources:
        limits:
          cpu: 10m
          memory: 128Mi
        requests:
          cpu: 1m
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_CHOWN
            - CAP_SETGID
            - CAP_SETUID
          drop:
            - ALL
        privileged: false
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
