version: '3.8'
services:
  db-postresql:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data-db-postresql:/var/lib/postgresql/data
volumes:
  data-db-postresql:
    driver: local
networks:
  default:
    external:
      name: nginx-certbot_default
