version: '3.8'
services:
    camunda-bpm-platform:
        image: camunda/camunda-bpm-platform:tomcat-7.14.0
        restart: always
        volumes:
            # Keep in sync with https://github.com/camunda/camunda-bpm-platform/blob/master/distro/tomcat/assembly/src/conf/bpm-platform.xml
            - ./camunda/conf/bpm-platform.xml:/camunda/conf/bpm-platform.xml
        environment:
            - DB_DRIVER=org.postgresql.Driver
            - DB_URL=jdbc:postgresql://db-postresql:5432/camunda-bpm-platform
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - WAIT_FOR=db-postresql:5432
            - WAIT_FOR_TIMEOUT=60
networks:
    default:
        external:
            name: nginx-certbot_default
