apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: on-failure
  containers:
    - name: app
      image: docker.io/nextcloud:25
      imagePullPolicy: always
      env:
        - name: APACHE_DISABLE_REWRITE_IP
          value: 1
        - name: MAIL_DOMAIN
          value: "exploding-hamster.duckdns.org"
        - name: MAIL_FROM_ADDRESS
          value: "nextcloud@exploding-hamster.duckdns.org"
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: NEXTCLOUD_ADMIN_PASSWORD
        - name: NEXTCLOUD_ADMIN_USER
          value: "nextcloud"
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: "nextcloud.exploding-hamster nextcloud.exploding-hamster.duckdns.org"
        - name: OVERWRITECLIURL
          value: "https://nextcloud.exploding-hamster.duckdns.org"
        - name: OVERWRITEHOST
          value: "nextcloud.exploding-hamster.duckdns.org"
        - name: OVERWRITEPROTOCOL
          value: "https"
        - name: POSTGRES_DB
          value: "nextcloud_db"
        - name: POSTGRES_HOST
          value: "database"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          value: "nextcloud_db"
        - name: SMTP_AUTHTYPE
          value: "PLAIN"
        - name: SMTP_HOST
          value: "smtp"
        - name: SMTP_PORT
          value: 25
        - name: TRUSTED_PROXIES
          value: "dyndns"
      resources:
        requests:
          cpu: "10m"
          memory: "384Mi"
        limits:
          cpu: "750m"
          memory: "1536Mi"
      volumeMounts:
        - name: nextcloud-volume
          mountPath: /var/www/html
  volumes:
    - name: nextcloud-volume
      persistentVolumeClaim:
        claimName: nextcloud-pvc
