apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 896Gi
    requests:
      storage: 128Gi
