apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 256Mi
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 896Gi
    requests:
      storage: 128Gi
