apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
spec:
  automountServiceAccountToken: false
  restartPolicy: OnFailure
  containers:
    - name: app
      image: lscr.io/linuxserver/nextcloud:29.0.5@sha256:e99a0f41fd73a06560a94fa2904f08e791a046ee5d6d50f2700f5c9b3418e94b
      imagePullPolicy: Always
      env:
        - name: APACHE_DISABLE_REWRITE_IP
          value: "1"
        - name: MAIL_DOMAIN
          value: exploding-hamster.duckdns.org
        - name: MAIL_FROM_ADDRESS
          value: nextcloud@exploding-hamster.duckdns.org
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: NEXTCLOUD_ADMIN_PASSWORD
        - name: NEXTCLOUD_ADMIN_USER
          value: nextcloud
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.exploding-hamster nextcloud.exploding-hamster.duckdns.org
        - name: OVERWRITECLIURL
          value: https://nextcloud.exploding-hamster.duckdns.org
        - name: OVERWRITEHOST
          value: nextcloud.exploding-hamster.duckdns.org
        - name: OVERWRITEPROTOCOL
          value: https
        - name: PGID
          value: "1000"
        - name: POSTGRES_DB
          value: nextcloud_db
        - name: POSTGRES_HOST
          value: database
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nextcloud-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          value: nextcloud_db
        - name: PUID
          value: "1000"
        - name: SMTP_AUTHTYPE
          value: PLAIN
        - name: SMTP_HOST
          value: smtp-gateway
        - name: SMTP_PORT
          value: "8025"
        - name: TRUSTED_PROXIES
          value: dyndns
        - name: TZ
          value: Europe/Berlin
      resources:
        limits:
          cpu: 750m
          ephemeral-storage: 100Mi
          memory: 1536Mi
        requests:
          cpu: 10m
          memory: 384Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_CHOWN
            - CAP_DAC_OVERRIDE
            - CAP_NET_BIND_SERVICE
            - CAP_SETGID
            - CAP_SETUID
          drop:
            - ALL
        privileged: false
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: nextcloud-config-volume
          mountPath: /config
        - name: nextcloud-data-volume
          mountPath: /data
  volumes:
    - name: nextcloud-config-volume
      persistentVolumeClaim:
        claimName: nextcloud-config-pvc
    - name: nextcloud-data-volume
      persistentVolumeClaim:
        claimName: nextcloud-data-pvc
