version: '3.8'
services:
  gitlab:
    image: gitlab/gitlab-ce:13.5.4-ce.0
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.docklab.de:8929' # Defines the external URL of the docker container service in the network
        gitlab_rails['gitlab_shell_ssh_port'] = 2224 # Defines the port number of the external accessible ssh service.
        # These settings are documented in more detail at
        # https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config/gitlab.yml.example#L346
        gitlab_rails['ldap_enabled'] = true # Enables the ldap feature
        gitlab_rails['ldap_host'] = 'auth.inf.h-brs.de' # Sets the ldap hostname
        gitlab_rails['ldap_port'] = 389 # Defines the ldap port
        gitlab_rails['ldap_uid'] = 'uid' # Defines the ldap userid to access the ldap service
        gitlab_rails['ldap_encryption'] = 'start_tls' # "start_tls" or "simple_tls" or "plain" as connection security
        gitlab_rails['ldap_allow_username_or_email_login'] = false # Allows to login with username and email into the gitlab service
        gitlab_rails['block_auto_created_users'] = false
        gitlab_rails['ldap_base'] = 'dc=FH-Bonn-Rhein-Sieg,dc=DE' # Base where we can search for users
        gitlab_rails['ldap_user_filter'] = '(uid=*)' # Base where we can search for users
        gitlab_rails['active_directory'] = true
        # gitlab_rails['ldap_bind_dn'] = 'cn=admin,dc=my_external_url,dc=com' # The full dn of the user you will bind with
        # gitlab_rails['ldap_password'] = 'password' # Defines the ldap password to access the ldap service
    volumes:
      - data-gitlab:/etc/gitlab
      - data-gitlab:/var/log/gitlab
      - data-gitlab:/var/opt/gitlab
volumes:
  data-gitlab:
    driver: local
networks:
  default:
    external:
      name: nginx-certbot_default
