apiVersion: v1
kind: Pod
metadata:
  name: https-nginx
  labels:
    app: https-nginx
    io.containers.autoupdate: image
spec:
  containers:
    - name: swag
      image: ghcr.io/linuxserver/swag:latest
      imagePullPolicy: always
      env:
        - name: EMAIL
          value: ""
        - name: ONLY_SUBDOMAINS
          value: FALSE
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: SUBDOMAINS
          value: "www,"
        - name: TZ
          value: "Europe/Berlin"
        - name: URL
          value: "yourdomain.url"
        - name: VALIDATION
          value: "http"
      ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
      resources:
        requests:
          cpu: "10m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      volumeMounts:
        - name: https-nginx-swag-volume
          mountPath: /config
  restartPolicy: Always
  volumes:
    - name: https-nginx-swag-volume
      persistentVolumeClaim:
        claimName: https-nginx-swag-volume-pvc
