apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: https-nginx-swag-volume-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
