apiVersion: v1
kind: Pod
metadata:
  name: dyndns
spec:
  automountServiceAccountToken: false
  containers:
    - name: dnsmasq
      image: docker.io/4km3/dnsmasq:2.90-r3@sha256:b032b8f2ced327f5fb8e312e01826c4f52586d7fc71321a895e58523d206edbb
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          ephemeral-storage: 100Mi
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_SETGID
            - CAP_SETUID
            - CAP_NET_BIND_SERVICE
            - NET_ADMIN
          drop:
            - ALL
        privileged: false
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
    - name: https
      image: ghcr.io/linuxserver/swag:4.1.1@sha256:361a1505f52813bbdc2836ea1d05b49ae687eb3bd1c742210fff58451eeaa78f
      imagePullPolicy: Always
      env:
        - name: DUCKDNSTOKEN
          valueFrom:
            secretKeyRef:
              name: dyndns-https-ip-secret
              key: DNSTOKEN
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: SUBDOMAINS
          value: wildcard
        - name: TZ
          value: Europe/Berlin
        - name: URL
          valueFrom:
            secretKeyRef:
              name: dyndns-https-ip-secret
              key: URL
        - name: VALIDATION
          value: duckdns
      ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          ephemeral-storage: 100Mi
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_CHOWN
            - CAP_DAC_OVERRIDE
            - CAP_FOWNER
            - CAP_NET_BIND_SERVICE
            - CAP_SETGID
            - CAP_SETUID
            - NET_ADMIN
          drop:
            - ALL
        privileged: false
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: dyndns-https-volume
          mountPath: /config
        - name: dyndns-https-configmap-volume
          mountPath: /config/nginx/site-confs/www.conf
          subPath: www.conf
    - name: ip
      image: ghcr.io/linuxserver/duckdns:latest@sha256:74d3b492ad40d1196888987938b359dd8f29e5fea065f7ce2a083c47bbadc2b9
      imagePullPolicy: Always
      env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: dyndns-https-ip-secret
              key: DNSTOKEN
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: SUBDOMAINS
          valueFrom:
            secretKeyRef:
              name: dyndns-https-ip-secret
              key: SUBDOMAINS
        - name: TZ
          value: Europe/Berlin
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_CHOWN
            - CAP_SETGID
            - CAP_SETUID
          drop:
            - ALL
        privileged: false
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: OnFailure
  volumes:
    - name: dyndns-https-volume
      persistentVolumeClaim:
        claimName: dyndns-https-pvc
    - name: dyndns-https-configmap-volume
      configMap:
        name: dyndns-https-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dyndns-https-configmap
data:
  www.conf: |
    # /config/nginx/site-confs/www.conf
    # redirect 3rd level domain to www 4th level domain
    # needed for duckdns wildcard certificates
    # only works with http. with https you'll need a valid certificate.
    
    server {
      server_name exploding-hamster.duckdns.org;
    
      return 301 https://www.$server_name$request_uri;
    }
