apiVersion: v1
kind: Pod
metadata:
  name: dyndns
spec:
  automountServiceAccountToken: false
  restartPolicy: OnFailure
  containers:
    - name: https
      image: ghcr.io/linuxserver/swag:2.11.0@sha256:6ed737b53ba6a554973292413a85f0ada74ce28c396ae8b6d4d38316cac312ef
      imagePullPolicy: Always
      env:
        - name: DUCKDNSTOKEN
          valueFrom:
            secretKeyRef:
              name: dyndns-https-ip-secret
              key: DNSTOKEN
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: SUBDOMAINS
          value: wildcard
        - name: TZ
          value: Europe/Berlin
        - name: URL
          valueFrom:
            secretKeyRef:
              name: dyndns-https-ip-secret
              key: URL
        - name: VALIDATION
          value: duckdns
      ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          ephemeral-storage: 100Mi
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_CHOWN
            - CAP_DAC_OVERRIDE
            - CAP_FOWNER
            - CAP_NET_BIND_SERVICE
            - CAP_SETGID
            - CAP_SETUID
            - NET_ADMIN
          drop:
            - ALL
        privileged: false
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: dyndns-https-volume
          mountPath: /config
        - name: dyndns-https-configmap-volume
          mountPath: /config/nginx/site-confs/www.conf
          subPath: www.conf
    - name: ip
      image: ghcr.io/linuxserver/duckdns:latest@sha256:5d68a49f5efdb0493edc5b5d4d808900ed6f656ec8237db142403427a879b177
      imagePullPolicy: Always
      env:
        - name: TOKEN
          valueFrom:
            secretKeyRef:
              name: dyndns-https-ip-secret
              key: DNSTOKEN
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: SUBDOMAINS
          valueFrom:
            secretKeyRef:
              name: dyndns-https-ip-secret
              key: SUBDOMAINS
        - name: TZ
          value: Europe/Berlin
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_CHOWN
            - CAP_SETGID
            - CAP_SETUID
          drop:
            - ALL
        privileged: false
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
  volumes:
    - name: dyndns-https-volume
      persistentVolumeClaim:
        claimName: dyndns-https-pvc
    - name: dyndns-https-configmap-volume
      configMap:
        name: dyndns-https-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dyndns-https-configmap
data:
  www.conf: |
    # /config/nginx/site-confs/www.conf
    # redirect 3rd level domain to www 4th level domain
    # needed for duckdns wildcard certificates
    # only works with http. with https you'll need a valid certificate.
    
    server {
      server_name exploding-hamster.duckdns.org;
    
      return 301 https://www.$server_name$request_uri;
    }
