version: '3.9'
services:
  db-postresql:
    image: docker.io/postgres:13
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - my-network
    volumes:
      - data-db-postresql:/var/lib/postgresql/data
volumes:
  data-db-postresql:
    driver: local
networks:
  my-network: