apiVersion: v1
kind: Pod
metadata:
  name: notification
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: OnFailure
  containers:
    - name: smtp-gateway
      image: docker.io/yoryan/mailrise:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8025
          hostPort: 25
          name: smtp
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: notification-smtp-gateway-configmap-volume
          mountPath: /etc/mailrise.conf
          subPath: mailrise.conf
  volumes:
    - name: notification-smtp-gateway-configmap-volume
      configMap:
        name: notification-smtp-gateway-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-smtp-gateway-configmap
data:
  mailrise.conf: |
    # /etc/mailrise.conf

    configs:
      "*@exploding-hamster.duckdns.org":
        urls:
          - tgram://{bot_token}/{chat_id}/?overflow=split
