apiVersion: v1
kind: Pod
metadata:
  name: notification
spec:
  automountServiceAccountToken: false
  restartPolicy: OnFailure
  containers:
    - name: smtp-gateway
      image: ghcr.io/yoryan/mailrise:1.4.0@sha256:68e36cb35455564179f1a95f541339d4a01c4e662e0d498da6b14a2b911ae279
      imagePullPolicy: Always
      ports:
        - containerPort: 8025
          hostPort: 25
          name: smtp
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          ephemeral-storage: 100Mi
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 999
        runAsNonRoot: true
        runAsUser: 999
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: notification-smtp-gateway-configmap-volume
          mountPath: /etc/mailrise.conf
          subPath: mailrise.conf
  volumes:
    - name: notification-smtp-gateway-configmap-volume
      configMap:
        name: notification-smtp-gateway-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-smtp-gateway-configmap
data:
  mailrise.conf: |
    # /etc/mailrise.conf

    configs:
      "*@*":
        urls:
          - tgram://{bot_token}/{chat_id}/?overflow=split
