apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: OnFailure
  containers:
    - name: postgresql
      image:
        docker.io/bitnami/postgresql:15
      imagePullPolicy: Always
      env:
        - name: POSTGRESQL_ENABLE_LDAP
          value: yes
        - name: POSTGRESQL_LDAP_BASE_DN
          value: dc=exploding-hamster,dc=duckdns.org
        - name: POSTGRESQL_LDAP_PORT
          value: "3389"
        - name: POSTGRESQL_LDAP_SEARCH_FILTER
          value: (&(uid=$username)(cn=databases))
        - name: POSTGRESQL_LDAP_SERVER
          value: ldap
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRESQL_PASSWORD
      resources:
        limits:
          cpu: 250m
          memory: 1024Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_DAC_OVERRIDE
          drop:
            - ALL
        privileged: false
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: postgresql-volume
          mountPath: /bitnami/postgresql
  volumes:
    - name: postgresql-volume
      persistentVolumeClaim:
        claimName: postgresql-pvc
