apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borg-server-backup-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 1280Gi
    requests:
      storage: 128Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borg-server-ssh-keys-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 10Mi
    requests:
      storage: 1Mi