apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borg-server-backup-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1536Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: borg-server-ssh-keys-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi