apiVersion: v1
kind: Pod
metadata:
  name: borg-backup
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: OnFailure
  containers:
    - name: server
      image: docker.io/horaceworblehat/borg-server:2.0
      imagePullPolicy: Always
      env:
        - name: BORG_AUTHORIZED_KEYS
          valueFrom:
            secretKeyRef:
              name: borg-backup-server-secret
              key: AUTHORIZED_KEYS
        - name: BORG_UID
          value: "1000"
        - name: BORG_GID
          value: "1000"
      ports:
        - containerPort: 22
          hostPort: 26351
          name: ssh
          protocol: TCP
      resources:
        limits:
          cpu: 1000m
          memory: 4096Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_CHOWN
            - CAP_DAC_OVERRIDE
            - CAP_FOWNER
            - CAP_KILL
            - CAP_NET_BIND_SERVICE
            - CAP_SETGID
            - CAP_SETUID
            - CAP_SYS_CHROOT
          drop:
            - ALL
        privileged: false
        runAsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: borg-backup-server-backup-volume
          mountPath: /home/borg/backups
        - name: borg-backup-server-ssh-keys-volume
          mountPath: /var/lib/docker-borg
  volumes:
    - name: borg-backup-server-backup-volume
      persistentVolumeClaim:
        claimName: borg-backup-server-backup-pvc
    - name: borg-backup-server-ssh-keys-volume
      persistentVolumeClaim:
        claimName: borg-backup-server-ssh-keys-pvc
