apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    io.containers.autoupdate: registry
spec:
  restartPolicy: on-failure
  containers:
    - name: postgresql
      image:
        docker.io/bitnami/postgresql:15
      imagePullPolicy: always
      env:
        - name: POSTGRESQL_ENABLE_LDAP
          value: "yes"
        - name: POSTGRESQL_LDAP_SERVER
          value: "ldap://ldap"
        - name: POSTGRESQL_LDAP_PORT
          value: 3389
        - name: POSTGRESQL_LDAP_BASE_DN
          value: "dc=exploding-hamster,dc=duckdns.org"
        - name: POSTGRESQL_LDAP_BIND_DN
          value: "ou=database,dc=exploding-hamster,dc=duckdns.org"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRESQL_PASSWORD
      ports:
        - containerPort: 5432
          hostPort: 5432
          name: postgresql
          protocol: TCP
      resources:
        requests:
          cpu: "10m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "1024Mi"
      volumeMounts:
        - name: postgresql-volume
          mountPath: /bitnami/postgresql
  volumes:
    - name: postgresql-volume
      persistentVolumeClaim:
        claimName: postgresql-pvc
