apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ovhcom-beamium-volume-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
