apiVersion: v1
kind: Pod
metadata:
  name: borg-backup
spec:
  automountServiceAccountToken: false
  restartPolicy: OnFailure
  containers:
    - name: client
      image: ghcr.io/borgmatic-collective/borgmatic:msmtp-1.7@sha256:736c44f00ff70245934cbdf7810d71aed5ccb6999988fff8b2584570f1568429
      imagePullPolicy: Always
      env:
        - name: BORG_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: borg-backup-client-secret
              key: BORG_PASSPHRASE
        - name: TZ
          value: Europe/Berlin
      resources:
        limits:
          cpu: 1000m
          ephemeral-storage: 100Mi
          memory: 4096Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - CAP_DAC_READ_SEARCH
            - CAP_SETGID
          drop:
            - ALL
        privileged: false
        runAsGroup: 0
        runAsNonRoot: true
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: borg-backup-client-cache-volume
          mountPath: /root/.cache/borg
        - name: borg-backup-client-config-volume
          mountPath: /root/.config/borg
        - name: borg-backup-client-configmap-volume
          mountPath: /etc/borgmatic.d/msmtp.env
          subPath: msmtp.env
        - name: borg-backup-client-etc-borgmatic-volume
          mountPath: /etc/borgmatic.d/
        - name: borg-backup-client-ssh-volume
          mountPath: /root/.ssh
        - name: ci-drone.io-server-data-volume
          mountPath: /mnt/source/ci-drone.io-server-data
          readOnly: true
        - name: dyndns-https-volume
          mountPath: /mnt/source/dyndns-https
          readOnly: true
        - name: ldap-volume
          mountPath: /mnt/source/ldap
          readOnly: true
        - name: nextcloud-volume
          mountPath: /mnt/source/nextcloud
          readOnly: true
        - name: postgresql-volume
          mountPath: /mnt/source/postgresql
          readOnly: true
  volumes:
    - name: borg-backup-client-cache-volume
      persistentVolumeClaim:
        claimName: borg-backup-client-cache-pvc
    - name: borg-backup-client-config-volume
      persistentVolumeClaim:
        claimName: borg-backup-client-config-pvc
    - name: borg-backup-client-configmap-volume
      configMap:
        name: borg-backup-client-configmap
    - name: borg-backup-client-etc-borgmatic-volume
      persistentVolumeClaim:
        claimName: borg-backup-client-etc-borgmatic-pvc
    - name: borg-backup-client-ssh-volume
      persistentVolumeClaim:
        claimName: borg-backup-client-ssh-pvc
    - name: ci-drone.io-server-data-volume
      persistentVolumeClaim:
        claimName: ci-drone.io-server-data-pvc
    - name: dyndns-https-volume
      persistentVolumeClaim:
        claimName: dyndns-https-pvc
    - name: ldap-volume
      persistentVolumeClaim:
        claimName: ldap-pvc
    - name: nextcloud-volume
      persistentVolumeClaim:
        claimName: nextcloud-pvc
    - name: postgresql-volume
      persistentVolumeClaim:
        claimName: postgresql-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: borg-backup-client-configmap
data:
  msmtp.env: |
    # /etc/borgmatic.d/msmtp.env
    
    MAIL_RELAY_HOST=smtp-gateway
    MAIL_PORT=8025
    
    # smtp auth method: on,off,login...
    MAIL_AUTH_METHOD=off
    
    # set tls on, off
    MAIL_TLS=off
    
    # set starttls on, off
    MAIL_STARTTLS=off
    
    MAIL_FROM=borg-backup-client@exploding-hamster.duckdns.org
    MAIL_TO=borg-backup-client@exploding-hamster.duckdns.org
    MAIL_SUBJECT="Borg backup of server exploding-hamster.duckdns.org"
